root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []
bin = "/usr/bin/supervisorctl restart revad:*"
cmd = "make revad && /usr/bin/supervisorctl stop revad:* && cp cmd/revad/revad /usr/bin/revad"
delay = 1000
exclude_dir = [
  "assets",
  "tmp",
  "vendor",
  "testdata",
  "docs",
  "changelog",
  "examples",
  "tests",
  "vendor-bin",
]
exclude_file = ["cmd/revad/revad", "cmd/reva/reva"]
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html"]
kill_delay = "0s"
log = "build-errors.log"
send_interrupt = false
stop_on_error = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
